### ISSUE TITLE
Menu déroulant 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/mon-impact-transport#1]
Il faudrait peut-être marquer davantage le menu déroulant, pas forcément assez clair avec le petite flèche (je l'ai pas tout de suite vu quand j'ai fait mes tests) 
=> ex Grossir la flèche ou intégrer un autre marqueur pour pousser à cliquer 

+ grossir peut-être les propositions (un peu petit?)

**Comment by martinregner** [comment]
En effet, pas facile à voir. C'est dommage, la nouvelle fonction "de ... à ... " est top !

Les choix aussi apparaissent assez petits sur Chrome, avec un espace entre :
![image](https://user-images.githubusercontent.com/46482115/110459485-548b5300-80cd-11eb-9b71-395ab0e44338.png)

Et je trouve que "**aller chercher du pain**" et "**aller au travail**" perdent de leur sens avec la fonction le "de ... a". Pour modifier la distance par défaut en tant qu'utilisateur, il faut repasser par le menu déroulant.
Sinon, comme pour le "je parcours", **laisser le champs km modifiable** ? au lieu de le mettre dessous en petit, le mettre à côté et modifiable ?
Si pas trop compliqué, on peut garder la même logique pour toutes les lignes qui proposent une distance par défaut.

**Comment by martinregner** [comment]
cf. également #31 : les choix comme **retirer "aller chercher du pain" et "aller au travail"** (mais aussi les autres...) qui peuvent aussi être des freins à l'intégration pour des entreprises.

**Proposition : retirer ces propositions par défaut et n'avoir que : "de...à.." ou "x km"**

**Comment by florianpanchout** [comment]
Done
