### ISSUE TITLE
Ajout de la construction : modifier les textes

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/mon-impact-transport#119]
Maintenant que la construction a été ajoutée, il faudrait modifier le texte dans les pop-in sources et sur le simulateur : 

>Équivalent CO₂ par personne en France. Sont incluses les émissions directes, et la production et distribution de carburant et d'électricité. La construction des véhicules (voiture, vélo, batterie, train, avion...) et des infrastructures (routes, rails, aéroports...) n'est pas incluse.

>Voiture (thermique)
193 gCO2e/km/véhicule ; Base Carbone ADEME, moyenne nationale toutes distances, toutes carburations.
Les données intègrent l’amont et la combustion du carburant. Comme pour les autres modes de transports, elles n’intègrent pas la fabrication des véhicules et les émissions liées aux infrastructures routières.

> Voiture (électrique)
19,8 gCO2e/km/véhicule ; Base Carbone ADEME, Véhicule Electrique compact - "Coeur de gamme".
Les données intègrent les émissions liées à l'électricité pour recharger le véhicule. Comme pour les autres modes de transports, elles n’intègrent pas la fabrication des véhicules et les émissions liées aux infrastructures routières.

Etc.

**Comment by florianpanchout** [comment]
Done
