### ISSUE TITLE
Bugs API CORS policy

### ISSUE THREAD

**Issue by ldupuy-insa** [datagir/mon-impact-transport#137]
Bonjour,

À l'INSA Lyon nous développons une application de précommande d'ordre mission en proposant des fonctionnalités de calcul d'empreintes carbones et la possibilité de générer des extractions. L'objectif est de faire de la prévention et de réduire nos impacts.

Pour cela, nous utilisons votre API **api.monimpacttransport.fr**, mais depuis le mise en Prod de notre application nous ne pouvons plus requêter le endpoint **callGMap**.

En voulant télécharger les sources de l'application et l'executer en local pour effectuer des tests, nous avons le même souci. Cela provient des règles **CORS policy**.

Le endpoint **https://monimpacttransport.fr/.netlify/functions/callGMapSearch** fonctionne bien, car les headers cors sont bien configurés côté serveur :

```text
# Entête de la réponse HTTP
access-control-allow-headers: Content-Type
access-control-allow-methods: GET, POST, OPTION
access-control-allow-origin: *
```

En revanche le requêtage du endpoint **https://monimpacttransport.fr/.netlify/functions/callGMap** ne contient pas de headers `access-control-allow-...` dans la réponse HTTP et provoque l'erreur JavaScript :
```text
'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
Serait-il possible d'avoir de l'aide afin de corriger ce problème ? Nous pouvons également organiser une rencontre pour vous présenter l'application.

Bien cordialement,

Lucas

**Comment by florianpanchout** [comment]
Bonjour,

Merci pour votre message. Il s'agit du fonctionnement normal de l'API : Seul le endpoint `/getEmissionsPerDistance` est disponible publiquement.

Bonne journée,

Florian
