### ISSUE TITLE
API non fonctionnelle le 28-09-2023

### ISSUE THREAD

**Issue by tomasbastien** [datagir/mon-impact-transport#138]
Bonjour,

Il semblerait que l'API publiée sur https://api.monimpacttransport.fr/ ne soit plus accessible depuis l'extérieur depuis cet après-midi (ok ce matin): 

Ex : https://api.monimpacttransport.fr/beta/getEmissionsPerDistance?km=1089.297&transportations=9
renvoie : 

**Erreur 400 - Bad Request**
_**Cycle Prohibited**
Description: Could not process your request for the document because it would cause an HTTP proxy cycle. Please check the URL and your browser's proxy settings._

Il y a t-il des actions en cours de votre côté ?

Cordialement,

**Comment by bdavidxyz** [comment]
Bonjour, c'est réparé :)
