### ISSUE TITLE
Valoriser trajet de ville à ville 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/mon-impact-transport#2]
Je suis d'accord avec le fait de ne pas tout mettre au même niveau : les trajets de ville à ville c'est top ! 
Je pense qu'il faudrait davantage le mettre en avant directement sur le calculateur ou alors le valoriser dans le menu déroulant

**Comment by florianpanchout** [comment]
Done

**Comment by martinregner** [comment]
- préciser aussi dans la parenthèse en dessous de la ville d'arrivée : "(xx km **à vol d'oiseau**)"
- à tester selon son utilisation, mais il n'est pas forcément facilement visible. Peut-être jouer l'animation entre les deux points sur le petit onglet aussi lorsque l'on est pas dessus ? ex. toutes les 3sec ?

**Comment by florianpanchout** [comment]
Yes, j'ai prévu d'animer les deux boutons et l'input km après un temps d'inactivité

**Comment by florianpanchout** [comment]
Fait

**Comment by martinregner** [comment]
Top !
