### ISSUE TITLE
Max 31km pour le vélo

### ISSUE THREAD

**Issue by fjg** [datagir/mon-impact-transport#27]
Bonjour
Etonnant qu'à partir de 31 km le vélo ne soit plus considéré comme un mode de transport pertinent. Et la marche au delà de 10 km. Dans le Défi "J'y vais" que nous organisons en ce moment avec l'ADEME Grand Est, nous avons des participants qui peuvent faire plus de km par jour, ou qui souhaitent savoir ce que représenteraient leurs émissions sur une semaine en cumulant les km parcourus comparativement à d'autres modes. C'est dommage que le calculateur se limite ainsi. Nous l'aurions mis en lien sur le site et en info sur la page FB !

**Comment by fjg** [comment]
Mettre l'option voyage à vélo pour l'option "voyager dans le monde". Ce n'est effectivement pas une utopie :) https://poitiersnoumea.wordpress.com/
Bien à vous, Victor

**Comment by fjg** [comment]
pourquoi avoir limité le vélo à 30km ? dans la réalité les personnes ayant des trajets supérieurs à 30km sans vae et bien... cela existe !

**Comment by fjg** [comment]
Mais... pourquoi lorsqu'on sélectionne un distance importante les modes doux sont absents? Je voulais calculer l'impact carbone d'une randonnée vélo de 174km avec un vélo normale et un vélo électrique mais parmi les résultats le vélo absent. Pas de souci pour faire une multiplication avec une distance inférieure. Mais bon un peu d'ambition pour votre calculateur ;)

**Comment by florianpanchout** [comment]
Corrigé par la nouvelle version
