### ISSUE TITLE
Popup forcage radiatif

### ISSUE THREAD

**Issue by fjg** [datagir/mon-impact-transport#36]
Proposition de texte : 

> L'impact de l'avion ne se limite pas aux émissions de CO2 dues à la combustion du kérosène pour à sa fabrication, mais il implique d'autres effets liées aux traînées, émissions d'autres particules NOx, etc. On peut alors utiliser le [forçage radiatif](https://fr.wikipedia.org/wiki/For%C3%A7age_radiatif) pour mesurer tous les effets. A ce jour il existe une grande incertitude quant à ces effets (facteur x2, x3...). Des recherches sont menées pour préciser encore ces impacts.

**Comment by martinregner** [comment]
Cf. #3 je préférerais garder les deux couleurs de barre (consensus trouvé en septembre avec les collègues), et donc garder un texte proche de l'existant : 

> Les deux parties de la barre représentent l'impact du vol sans (à gauche) et avec (à droite, en dégradé) prise en compte de l'impact induit des traînées de condensation, tel que présenté dans la Base Carbone de l'ADEME. Du fait que les avions volent à haute altitude, la combustion du kérosène crée des traînées et perturbe les cycles d’autres gaz à effet de serre que le CO2 (vapeur d'eau, eau condensée sous diverses formes, NOx et méthane qui, ensemble, produisent de l'ozone, etc.) : c'est cet impact additionnel (dit forçage radiatif additionnel) qui est représenté par la partie de droite de la barre.
