### ISSUE TITLE
Ajouter un bouton "Voir tous les modes de transport"

### ISSUE THREAD

**Issue by martinregner** [datagir/mon-impact-transport#45]
Il n'est pas forcément évident de penser à cliquer sur la roue crantée pour ajouter d'autres modes.
Un petit bouton ou une ligne en violet sous la dernière barre, par ex. "Voir tous les modes de transport" et qui ouvre le volet latéral, permettrait je pense de mieux mettre cela en avant.
Qu'en penses-tu ?

**Comment by florianpanchout** [comment]
Ce bouton ne s'affichait que sur mobile (en l'absence de la roue crantée). Il s'affiche maintenant tout le temps

**Comment by martinregner** [comment]
Ok nickel !
