### ISSUE TITLE
 Trajets maritimes (Simulation Paris-NY)

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/mon-impact-transport#46]
On s'en était déjà parlé mais je pense qu'on risque d'avoir des retours utilisateurs sur les trajets qui traversent l'eau et qui suggèrent quand même les transports au sol (type Europe-Amérique, Europe-Afrique etc)

=> à défaut de pouvoir filtrer parce que trop compliqué, mettre un petit "i" information, qui dit que nous sommes conscients de ces paramètres mais pas assez de données sur les données maritimes etc. et que le calculateur se base sur des trajets "en général" sans prendre en compte la " typologie du trajet" ?

**Comment by martinregner** [comment]
Sinon ajouter un mode de transport "Bateau" mais que l'on ne peut pas sélectionner, avec un petit tooltip qui dit qu'il n'a y a pas encore de données consolidées ?

**Comment by florianpanchout** [comment]
Le texte en bas ne suffit pas ?
 
"Les distances données par le mode itinéraire sont calculées à vol d'oiseau et ne correspondent pas à la réalité des transports."

**Comment by florianpanchout** [comment]
J'ai ajouté une modal au clic sur "à vol d'oiseau". Il y a probablement mieux à faire comme texte

**Comment by martinregner** [comment]
Parfait la modal 👍 

Proposition d'amélioration :

> Lorsque vous ne connaissez pas directement le kilométrage, le mode itinéraire vous permet d'estimer la distance entre deux points. Calculée à vol d'oiseau, cette distance est identique pour tous les modes de déplacement et ne correspond pas à la réalité des transports disponibles sur ce trajet.

**Comment by florianpanchout** [comment]
Fait

**Comment by martinregner** [comment]
Remettre le même texte en dessous du graphe non ?...
(même si ça commence à faire beaucoup de texte)

**Comment by florianpanchout** [comment]
C'est fait. J'en ai profité pour mettre un lien vers le mode itinéraire

**Comment by martinregner** [comment]
impec ! 👍
