### ISSUE TITLE
bouton pour changer de mode km/trajet sur iframe fond blanc

### ISSUE THREAD

**Issue by martinregner** [datagir/mon-impact-transport#49]
Sur fond blanc, le petit onglet pour changer de mode n'est pas "fermé" ; je propose d'ajouter un trait horizontal pour le rendre plus visible / compréhensible :
![image](https://user-images.githubusercontent.com/46482115/111503670-3e256d00-8747-11eb-9dca-fbae9b5146bd.png)

**Comment by florianpanchout** [comment]
Fait
