### ISSUE TITLE
Mode de transport inactifs

### ISSUE THREAD

**Issue by florianpanchout** [datagir/mon-impact-transport#53]
Quels modes de transport inactifs (sans data et donc non sélectionnables) veut on afficher ?

**Comment by martinregner** [comment]
- Bus (électrique)
- Véhicule hydrogène
- Ferry / bateau
- Bateau à moteur
- Scooter & moto légère (électrique)

Proposition de tooltip :
> Pas de donnée disponible pour ce mode de transport

**Comment by florianpanchout** [comment]
Done

**Comment by martinregner** [comment]
Top ! 👍
